// Code generated by go-swagger; DO NOT EDIT.

package virtualization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// VirtualizationClustersDeleteReader is a Reader for the VirtualizationClustersDelete structure.
type VirtualizationClustersDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualizationClustersDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewVirtualizationClustersDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewVirtualizationClustersDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewVirtualizationClustersDeleteNoContent creates a VirtualizationClustersDeleteNoContent with default headers values
func NewVirtualizationClustersDeleteNoContent() *VirtualizationClustersDeleteNoContent {
	return &VirtualizationClustersDeleteNoContent{}
}

/* VirtualizationClustersDeleteNoContent describes a response with status code 204, with default header values.

VirtualizationClustersDeleteNoContent virtualization clusters delete no content
*/
type VirtualizationClustersDeleteNoContent struct {
}

func (o *VirtualizationClustersDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /virtualization/clusters/{id}/][%d] virtualizationClustersDeleteNoContent ", 204)
}

func (o *VirtualizationClustersDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewVirtualizationClustersDeleteDefault creates a VirtualizationClustersDeleteDefault with default headers values
func NewVirtualizationClustersDeleteDefault(code int) *VirtualizationClustersDeleteDefault {
	return &VirtualizationClustersDeleteDefault{
		_statusCode: code,
	}
}

/* VirtualizationClustersDeleteDefault describes a response with status code -1, with default header values.

VirtualizationClustersDeleteDefault virtualization clusters delete default
*/
type VirtualizationClustersDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the virtualization clusters delete default response
func (o *VirtualizationClustersDeleteDefault) Code() int {
	return o._statusCode
}

func (o *VirtualizationClustersDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /virtualization/clusters/{id}/][%d] virtualization_clusters_delete default  %+v", o._statusCode, o.Payload)
}
func (o *VirtualizationClustersDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *VirtualizationClustersDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
