/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.0-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// VirtualizationVirtualMachinesCreateRequest - struct for VirtualizationVirtualMachinesCreateRequest
type VirtualizationVirtualMachinesCreateRequest struct {
	WritableVirtualMachineWithConfigContextRequest        *WritableVirtualMachineWithConfigContextRequest
	ArrayOfWritableVirtualMachineWithConfigContextRequest *[]WritableVirtualMachineWithConfigContextRequest
}

// WritableVirtualMachineWithConfigContextRequestAsVirtualizationVirtualMachinesCreateRequest is a convenience function that returns WritableVirtualMachineWithConfigContextRequest wrapped in VirtualizationVirtualMachinesCreateRequest
func WritableVirtualMachineWithConfigContextRequestAsVirtualizationVirtualMachinesCreateRequest(v *WritableVirtualMachineWithConfigContextRequest) VirtualizationVirtualMachinesCreateRequest {
	return VirtualizationVirtualMachinesCreateRequest{
		WritableVirtualMachineWithConfigContextRequest: v,
	}
}

// []WritableVirtualMachineWithConfigContextRequestAsVirtualizationVirtualMachinesCreateRequest is a convenience function that returns []WritableVirtualMachineWithConfigContextRequest wrapped in VirtualizationVirtualMachinesCreateRequest
func ArrayOfWritableVirtualMachineWithConfigContextRequestAsVirtualizationVirtualMachinesCreateRequest(v *[]WritableVirtualMachineWithConfigContextRequest) VirtualizationVirtualMachinesCreateRequest {
	return VirtualizationVirtualMachinesCreateRequest{
		ArrayOfWritableVirtualMachineWithConfigContextRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *VirtualizationVirtualMachinesCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into WritableVirtualMachineWithConfigContextRequest
	err = newStrictDecoder(data).Decode(&dst.WritableVirtualMachineWithConfigContextRequest)
	if err == nil {
		jsonWritableVirtualMachineWithConfigContextRequest, _ := json.Marshal(dst.WritableVirtualMachineWithConfigContextRequest)
		if string(jsonWritableVirtualMachineWithConfigContextRequest) == "{}" { // empty struct
			dst.WritableVirtualMachineWithConfigContextRequest = nil
		} else {
			if err = validator.Validate(dst.WritableVirtualMachineWithConfigContextRequest); err != nil {
				dst.WritableVirtualMachineWithConfigContextRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.WritableVirtualMachineWithConfigContextRequest = nil
	}

	// try to unmarshal data into ArrayOfWritableVirtualMachineWithConfigContextRequest
	err = newStrictDecoder(data).Decode(&dst.ArrayOfWritableVirtualMachineWithConfigContextRequest)
	if err == nil {
		jsonArrayOfWritableVirtualMachineWithConfigContextRequest, _ := json.Marshal(dst.ArrayOfWritableVirtualMachineWithConfigContextRequest)
		if string(jsonArrayOfWritableVirtualMachineWithConfigContextRequest) == "{}" { // empty struct
			dst.ArrayOfWritableVirtualMachineWithConfigContextRequest = nil
		} else {
			if err = validator.Validate(dst.ArrayOfWritableVirtualMachineWithConfigContextRequest); err != nil {
				dst.ArrayOfWritableVirtualMachineWithConfigContextRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfWritableVirtualMachineWithConfigContextRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.WritableVirtualMachineWithConfigContextRequest = nil
		dst.ArrayOfWritableVirtualMachineWithConfigContextRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(VirtualizationVirtualMachinesCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(VirtualizationVirtualMachinesCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src VirtualizationVirtualMachinesCreateRequest) MarshalJSON() ([]byte, error) {
	if src.WritableVirtualMachineWithConfigContextRequest != nil {
		return json.Marshal(&src.WritableVirtualMachineWithConfigContextRequest)
	}

	if src.ArrayOfWritableVirtualMachineWithConfigContextRequest != nil {
		return json.Marshal(&src.ArrayOfWritableVirtualMachineWithConfigContextRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *VirtualizationVirtualMachinesCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.WritableVirtualMachineWithConfigContextRequest != nil {
		return obj.WritableVirtualMachineWithConfigContextRequest
	}

	if obj.ArrayOfWritableVirtualMachineWithConfigContextRequest != nil {
		return obj.ArrayOfWritableVirtualMachineWithConfigContextRequest
	}

	// all schemas are nil
	return nil
}

type NullableVirtualizationVirtualMachinesCreateRequest struct {
	value *VirtualizationVirtualMachinesCreateRequest
	isSet bool
}

func (v NullableVirtualizationVirtualMachinesCreateRequest) Get() *VirtualizationVirtualMachinesCreateRequest {
	return v.value
}

func (v *NullableVirtualizationVirtualMachinesCreateRequest) Set(val *VirtualizationVirtualMachinesCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualizationVirtualMachinesCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualizationVirtualMachinesCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualizationVirtualMachinesCreateRequest(val *VirtualizationVirtualMachinesCreateRequest) *NullableVirtualizationVirtualMachinesCreateRequest {
	return &NullableVirtualizationVirtualMachinesCreateRequest{value: val, isSet: true}
}

func (v NullableVirtualizationVirtualMachinesCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualizationVirtualMachinesCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
