/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.2.2 (4.2)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// RackFormFactorValue * `2-post-frame` - 2-post frame * `4-post-frame` - 4-post frame * `4-post-cabinet` - 4-post cabinet * `wall-frame` - Wall-mounted frame * `wall-frame-vertical` - Wall-mounted frame (vertical) * `wall-cabinet` - Wall-mounted cabinet * `wall-cabinet-vertical` - Wall-mounted cabinet (vertical)
type RackFormFactorValue string

// List of Rack_form_factor_value
const (
	RACKFORMFACTORVALUE__2_POST_FRAME RackFormFactorValue = "2-post-frame"
	RACKFORMFACTORVALUE__4_POST_FRAME RackFormFactorValue = "4-post-frame"
	RACKFORMFACTORVALUE__4_POST_CABINET RackFormFactorValue = "4-post-cabinet"
	RACKFORMFACTORVALUE_WALL_FRAME RackFormFactorValue = "wall-frame"
	RACKFORMFACTORVALUE_WALL_FRAME_VERTICAL RackFormFactorValue = "wall-frame-vertical"
	RACKFORMFACTORVALUE_WALL_CABINET RackFormFactorValue = "wall-cabinet"
	RACKFORMFACTORVALUE_WALL_CABINET_VERTICAL RackFormFactorValue = "wall-cabinet-vertical"
	RACKFORMFACTORVALUE_EMPTY RackFormFactorValue = ""
)

// All allowed values of RackFormFactorValue enum
var AllowedRackFormFactorValueEnumValues = []RackFormFactorValue{
	"2-post-frame",
	"4-post-frame",
	"4-post-cabinet",
	"wall-frame",
	"wall-frame-vertical",
	"wall-cabinet",
	"wall-cabinet-vertical",
	"",
}

func (v *RackFormFactorValue) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RackFormFactorValue(value)
	for _, existing := range AllowedRackFormFactorValueEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RackFormFactorValue", value)
}

// NewRackFormFactorValueFromValue returns a pointer to a valid RackFormFactorValue
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRackFormFactorValueFromValue(v string) (*RackFormFactorValue, error) {
	ev := RackFormFactorValue(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RackFormFactorValue: valid values are %v", v, AllowedRackFormFactorValueEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RackFormFactorValue) IsValid() bool {
	for _, existing := range AllowedRackFormFactorValueEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Rack_form_factor_value value
func (v RackFormFactorValue) Ptr() *RackFormFactorValue {
	return &v
}

type NullableRackFormFactorValue struct {
	value *RackFormFactorValue
	isSet bool
}

func (v NullableRackFormFactorValue) Get() *RackFormFactorValue {
	return v.value
}

func (v *NullableRackFormFactorValue) Set(val *RackFormFactorValue) {
	v.value = val
	v.isSet = true
}

func (v NullableRackFormFactorValue) IsSet() bool {
	return v.isSet
}

func (v *NullableRackFormFactorValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRackFormFactorValue(val *RackFormFactorValue) *NullableRackFormFactorValue {
	return &NullableRackFormFactorValue{value: val, isSet: true}
}

func (v NullableRackFormFactorValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRackFormFactorValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

