/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.0-Docker-3.4.2 (4.5)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// TenancyTenantsCreateRequest - struct for TenancyTenantsCreateRequest
type TenancyTenantsCreateRequest struct {
	TenantRequest        *TenantRequest
	ArrayOfTenantRequest *[]TenantRequest
}

// TenantRequestAsTenancyTenantsCreateRequest is a convenience function that returns TenantRequest wrapped in TenancyTenantsCreateRequest
func TenantRequestAsTenancyTenantsCreateRequest(v *TenantRequest) TenancyTenantsCreateRequest {
	return TenancyTenantsCreateRequest{
		TenantRequest: v,
	}
}

// []TenantRequestAsTenancyTenantsCreateRequest is a convenience function that returns []TenantRequest wrapped in TenancyTenantsCreateRequest
func ArrayOfTenantRequestAsTenancyTenantsCreateRequest(v *[]TenantRequest) TenancyTenantsCreateRequest {
	return TenancyTenantsCreateRequest{
		ArrayOfTenantRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *TenancyTenantsCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into TenantRequest
	err = newStrictDecoder(data).Decode(&dst.TenantRequest)
	if err == nil {
		jsonTenantRequest, _ := json.Marshal(dst.TenantRequest)
		if string(jsonTenantRequest) == "{}" { // empty struct
			dst.TenantRequest = nil
		} else {
			if err = validator.Validate(dst.TenantRequest); err != nil {
				dst.TenantRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.TenantRequest = nil
	}

	// try to unmarshal data into ArrayOfTenantRequest
	err = newStrictDecoder(data).Decode(&dst.ArrayOfTenantRequest)
	if err == nil {
		jsonArrayOfTenantRequest, _ := json.Marshal(dst.ArrayOfTenantRequest)
		if string(jsonArrayOfTenantRequest) == "{}" { // empty struct
			dst.ArrayOfTenantRequest = nil
		} else {
			if err = validator.Validate(dst.ArrayOfTenantRequest); err != nil {
				dst.ArrayOfTenantRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfTenantRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.TenantRequest = nil
		dst.ArrayOfTenantRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TenancyTenantsCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TenancyTenantsCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TenancyTenantsCreateRequest) MarshalJSON() ([]byte, error) {
	if src.TenantRequest != nil {
		return json.Marshal(&src.TenantRequest)
	}

	if src.ArrayOfTenantRequest != nil {
		return json.Marshal(&src.ArrayOfTenantRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TenancyTenantsCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.TenantRequest != nil {
		return obj.TenantRequest
	}

	if obj.ArrayOfTenantRequest != nil {
		return obj.ArrayOfTenantRequest
	}

	// all schemas are nil
	return nil
}

type NullableTenancyTenantsCreateRequest struct {
	value *TenancyTenantsCreateRequest
	isSet bool
}

func (v NullableTenancyTenantsCreateRequest) Get() *TenancyTenantsCreateRequest {
	return v.value
}

func (v *NullableTenancyTenantsCreateRequest) Set(val *TenancyTenantsCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTenancyTenantsCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTenancyTenantsCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenancyTenantsCreateRequest(val *TenancyTenantsCreateRequest) *NullableTenancyTenantsCreateRequest {
	return &NullableTenancyTenantsCreateRequest{value: val, isSet: true}
}

func (v NullableTenancyTenantsCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenancyTenantsCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
