// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package circuits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CircuitsCircuitTypesBulkDeleteReader is a Reader for the CircuitsCircuitTypesBulkDelete structure.
type CircuitsCircuitTypesBulkDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CircuitsCircuitTypesBulkDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCircuitsCircuitTypesBulkDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCircuitsCircuitTypesBulkDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCircuitsCircuitTypesBulkDeleteNoContent creates a CircuitsCircuitTypesBulkDeleteNoContent with default headers values
func NewCircuitsCircuitTypesBulkDeleteNoContent() *CircuitsCircuitTypesBulkDeleteNoContent {
	return &CircuitsCircuitTypesBulkDeleteNoContent{}
}

/* CircuitsCircuitTypesBulkDeleteNoContent describes a response with status code 204, with default header values.

CircuitsCircuitTypesBulkDeleteNoContent circuits circuit types bulk delete no content
*/
type CircuitsCircuitTypesBulkDeleteNoContent struct {
}

func (o *CircuitsCircuitTypesBulkDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /circuits/circuit-types/][%d] circuitsCircuitTypesBulkDeleteNoContent ", 204)
}

func (o *CircuitsCircuitTypesBulkDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCircuitsCircuitTypesBulkDeleteDefault creates a CircuitsCircuitTypesBulkDeleteDefault with default headers values
func NewCircuitsCircuitTypesBulkDeleteDefault(code int) *CircuitsCircuitTypesBulkDeleteDefault {
	return &CircuitsCircuitTypesBulkDeleteDefault{
		_statusCode: code,
	}
}

/* CircuitsCircuitTypesBulkDeleteDefault describes a response with status code -1, with default header values.

CircuitsCircuitTypesBulkDeleteDefault circuits circuit types bulk delete default
*/
type CircuitsCircuitTypesBulkDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the circuits circuit types bulk delete default response
func (o *CircuitsCircuitTypesBulkDeleteDefault) Code() int {
	return o._statusCode
}

func (o *CircuitsCircuitTypesBulkDeleteDefault) Error() string {
	return fmt.Sprintf("[DELETE /circuits/circuit-types/][%d] circuits_circuit-types_bulk_delete default  %+v", o._statusCode, o.Payload)
}
func (o *CircuitsCircuitTypesBulkDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *CircuitsCircuitTypesBulkDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
