// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/netbox/models"
)

// IpamL2vpnsCreateReader is a Reader for the IpamL2vpnsCreate structure.
type IpamL2vpnsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamL2vpnsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewIpamL2vpnsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIpamL2vpnsCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIpamL2vpnsCreateCreated creates a IpamL2vpnsCreateCreated with default headers values
func NewIpamL2vpnsCreateCreated() *IpamL2vpnsCreateCreated {
	return &IpamL2vpnsCreateCreated{}
}

/* IpamL2vpnsCreateCreated describes a response with status code 201, with default header values.

IpamL2vpnsCreateCreated ipam l2vpns create created
*/
type IpamL2vpnsCreateCreated struct {
	Payload *models.L2VPN
}

func (o *IpamL2vpnsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /ipam/l2vpns/][%d] ipamL2vpnsCreateCreated  %+v", 201, o.Payload)
}
func (o *IpamL2vpnsCreateCreated) GetPayload() *models.L2VPN {
	return o.Payload
}

func (o *IpamL2vpnsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.L2VPN)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIpamL2vpnsCreateDefault creates a IpamL2vpnsCreateDefault with default headers values
func NewIpamL2vpnsCreateDefault(code int) *IpamL2vpnsCreateDefault {
	return &IpamL2vpnsCreateDefault{
		_statusCode: code,
	}
}

/* IpamL2vpnsCreateDefault describes a response with status code -1, with default header values.

IpamL2vpnsCreateDefault ipam l2vpns create default
*/
type IpamL2vpnsCreateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the ipam l2vpns create default response
func (o *IpamL2vpnsCreateDefault) Code() int {
	return o._statusCode
}

func (o *IpamL2vpnsCreateDefault) Error() string {
	return fmt.Sprintf("[POST /ipam/l2vpns/][%d] ipam_l2vpns_create default  %+v", o._statusCode, o.Payload)
}
func (o *IpamL2vpnsCreateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *IpamL2vpnsCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
