// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDcimVirtualChassisListParams creates a new DcimVirtualChassisListParams object
// with the default values initialized.
func NewDcimVirtualChassisListParams() *DcimVirtualChassisListParams {
	var ()
	return &DcimVirtualChassisListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDcimVirtualChassisListParamsWithTimeout creates a new DcimVirtualChassisListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDcimVirtualChassisListParamsWithTimeout(timeout time.Duration) *DcimVirtualChassisListParams {
	var ()
	return &DcimVirtualChassisListParams{

		timeout: timeout,
	}
}

// NewDcimVirtualChassisListParamsWithContext creates a new DcimVirtualChassisListParams object
// with the default values initialized, and the ability to set a context for a request
func NewDcimVirtualChassisListParamsWithContext(ctx context.Context) *DcimVirtualChassisListParams {
	var ()
	return &DcimVirtualChassisListParams{

		Context: ctx,
	}
}

// NewDcimVirtualChassisListParamsWithHTTPClient creates a new DcimVirtualChassisListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDcimVirtualChassisListParamsWithHTTPClient(client *http.Client) *DcimVirtualChassisListParams {
	var ()
	return &DcimVirtualChassisListParams{
		HTTPClient: client,
	}
}

/*DcimVirtualChassisListParams contains all the parameters to send to the API endpoint
for the dcim virtual chassis list operation typically these are written to a http.Request
*/
type DcimVirtualChassisListParams struct {

	/*Domain*/
	Domain *string
	/*ID*/
	ID *string
	/*Limit
	  Number of results to return per page.

	*/
	Limit *int64
	/*Offset
	  The initial index from which to return the results.

	*/
	Offset *int64
	/*Q*/
	Q *string
	/*Region*/
	Region *string
	/*RegionID*/
	RegionID *string
	/*Site*/
	Site *string
	/*SiteID*/
	SiteID *string
	/*Tag*/
	Tag *string
	/*Tenant*/
	Tenant *string
	/*TenantID*/
	TenantID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithTimeout(timeout time.Duration) *DcimVirtualChassisListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithContext(ctx context.Context) *DcimVirtualChassisListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithHTTPClient(client *http.Client) *DcimVirtualChassisListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithDomain(domain *string) *DcimVirtualChassisListParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetDomain(domain *string) {
	o.Domain = domain
}

// WithID adds the id to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithID(id *string) *DcimVirtualChassisListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetID(id *string) {
	o.ID = id
}

// WithLimit adds the limit to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithLimit(limit *int64) *DcimVirtualChassisListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithOffset(offset *int64) *DcimVirtualChassisListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithQ adds the q to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithQ(q *string) *DcimVirtualChassisListParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetQ(q *string) {
	o.Q = q
}

// WithRegion adds the region to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithRegion(region *string) *DcimVirtualChassisListParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetRegion(region *string) {
	o.Region = region
}

// WithRegionID adds the regionID to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithRegionID(regionID *string) *DcimVirtualChassisListParams {
	o.SetRegionID(regionID)
	return o
}

// SetRegionID adds the regionId to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetRegionID(regionID *string) {
	o.RegionID = regionID
}

// WithSite adds the site to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithSite(site *string) *DcimVirtualChassisListParams {
	o.SetSite(site)
	return o
}

// SetSite adds the site to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetSite(site *string) {
	o.Site = site
}

// WithSiteID adds the siteID to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithSiteID(siteID *string) *DcimVirtualChassisListParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetSiteID(siteID *string) {
	o.SiteID = siteID
}

// WithTag adds the tag to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithTag(tag *string) *DcimVirtualChassisListParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetTag(tag *string) {
	o.Tag = tag
}

// WithTenant adds the tenant to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithTenant(tenant *string) *DcimVirtualChassisListParams {
	o.SetTenant(tenant)
	return o
}

// SetTenant adds the tenant to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetTenant(tenant *string) {
	o.Tenant = tenant
}

// WithTenantID adds the tenantID to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) WithTenantID(tenantID *string) *DcimVirtualChassisListParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the dcim virtual chassis list params
func (o *DcimVirtualChassisListParams) SetTenantID(tenantID *string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *DcimVirtualChassisListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Domain != nil {

		// query param domain
		var qrDomain string
		if o.Domain != nil {
			qrDomain = *o.Domain
		}
		qDomain := qrDomain
		if qDomain != "" {
			if err := r.SetQueryParam("domain", qDomain); err != nil {
				return err
			}
		}

	}

	if o.ID != nil {

		// query param id
		var qrID string
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Q != nil {

		// query param q
		var qrQ string
		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {
			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}

	}

	if o.Region != nil {

		// query param region
		var qrRegion string
		if o.Region != nil {
			qrRegion = *o.Region
		}
		qRegion := qrRegion
		if qRegion != "" {
			if err := r.SetQueryParam("region", qRegion); err != nil {
				return err
			}
		}

	}

	if o.RegionID != nil {

		// query param region_id
		var qrRegionID string
		if o.RegionID != nil {
			qrRegionID = *o.RegionID
		}
		qRegionID := qrRegionID
		if qRegionID != "" {
			if err := r.SetQueryParam("region_id", qRegionID); err != nil {
				return err
			}
		}

	}

	if o.Site != nil {

		// query param site
		var qrSite string
		if o.Site != nil {
			qrSite = *o.Site
		}
		qSite := qrSite
		if qSite != "" {
			if err := r.SetQueryParam("site", qSite); err != nil {
				return err
			}
		}

	}

	if o.SiteID != nil {

		// query param site_id
		var qrSiteID string
		if o.SiteID != nil {
			qrSiteID = *o.SiteID
		}
		qSiteID := qrSiteID
		if qSiteID != "" {
			if err := r.SetQueryParam("site_id", qSiteID); err != nil {
				return err
			}
		}

	}

	if o.Tag != nil {

		// query param tag
		var qrTag string
		if o.Tag != nil {
			qrTag = *o.Tag
		}
		qTag := qrTag
		if qTag != "" {
			if err := r.SetQueryParam("tag", qTag); err != nil {
				return err
			}
		}

	}

	if o.Tenant != nil {

		// query param tenant
		var qrTenant string
		if o.Tenant != nil {
			qrTenant = *o.Tenant
		}
		qTenant := qrTenant
		if qTenant != "" {
			if err := r.SetQueryParam("tenant", qTenant); err != nil {
				return err
			}
		}

	}

	if o.TenantID != nil {

		// query param tenant_id
		var qrTenantID string
		if o.TenantID != nil {
			qrTenantID = *o.TenantID
		}
		qTenantID := qrTenantID
		if qTenantID != "" {
			if err := r.SetQueryParam("tenant_id", qTenantID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
