// Code generated by go-swagger; DO NOT EDIT.

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/digitalocean/go-netbox/netbox/models"
)

// DcimVirtualChassisListReader is a Reader for the DcimVirtualChassisList structure.
type DcimVirtualChassisListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimVirtualChassisListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDcimVirtualChassisListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDcimVirtualChassisListOK creates a DcimVirtualChassisListOK with default headers values
func NewDcimVirtualChassisListOK() *DcimVirtualChassisListOK {
	return &DcimVirtualChassisListOK{}
}

/*DcimVirtualChassisListOK handles this case with default header values.

DcimVirtualChassisListOK dcim virtual chassis list o k
*/
type DcimVirtualChassisListOK struct {
	Payload *models.DcimVirtualChassisListOKBody
}

func (o *DcimVirtualChassisListOK) Error() string {
	return fmt.Sprintf("[GET /dcim/virtual-chassis/][%d] dcimVirtualChassisListOK  %+v", 200, o.Payload)
}

func (o *DcimVirtualChassisListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DcimVirtualChassisListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
