// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/netbox/models"
)

// DcimCableTerminationsBulkUpdateReader is a Reader for the DcimCableTerminationsBulkUpdate structure.
type DcimCableTerminationsBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimCableTerminationsBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimCableTerminationsBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDcimCableTerminationsBulkUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimCableTerminationsBulkUpdateOK creates a DcimCableTerminationsBulkUpdateOK with default headers values
func NewDcimCableTerminationsBulkUpdateOK() *DcimCableTerminationsBulkUpdateOK {
	return &DcimCableTerminationsBulkUpdateOK{}
}

/* DcimCableTerminationsBulkUpdateOK describes a response with status code 200, with default header values.

DcimCableTerminationsBulkUpdateOK dcim cable terminations bulk update o k
*/
type DcimCableTerminationsBulkUpdateOK struct {
	Payload *models.CableTermination
}

func (o *DcimCableTerminationsBulkUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /dcim/cable-terminations/][%d] dcimCableTerminationsBulkUpdateOK  %+v", 200, o.Payload)
}
func (o *DcimCableTerminationsBulkUpdateOK) GetPayload() *models.CableTermination {
	return o.Payload
}

func (o *DcimCableTerminationsBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CableTermination)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimCableTerminationsBulkUpdateDefault creates a DcimCableTerminationsBulkUpdateDefault with default headers values
func NewDcimCableTerminationsBulkUpdateDefault(code int) *DcimCableTerminationsBulkUpdateDefault {
	return &DcimCableTerminationsBulkUpdateDefault{
		_statusCode: code,
	}
}

/* DcimCableTerminationsBulkUpdateDefault describes a response with status code -1, with default header values.

DcimCableTerminationsBulkUpdateDefault dcim cable terminations bulk update default
*/
type DcimCableTerminationsBulkUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the dcim cable terminations bulk update default response
func (o *DcimCableTerminationsBulkUpdateDefault) Code() int {
	return o._statusCode
}

func (o *DcimCableTerminationsBulkUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /dcim/cable-terminations/][%d] dcim_cable-terminations_bulk_update default  %+v", o._statusCode, o.Payload)
}
func (o *DcimCableTerminationsBulkUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimCableTerminationsBulkUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
