// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/netbox/models"
)

// DcimRackGroupsBulkUpdateReader is a Reader for the DcimRackGroupsBulkUpdate structure.
type DcimRackGroupsBulkUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimRackGroupsBulkUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimRackGroupsBulkUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDcimRackGroupsBulkUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimRackGroupsBulkUpdateOK creates a DcimRackGroupsBulkUpdateOK with default headers values
func NewDcimRackGroupsBulkUpdateOK() *DcimRackGroupsBulkUpdateOK {
	return &DcimRackGroupsBulkUpdateOK{}
}

/*DcimRackGroupsBulkUpdateOK handles this case with default header values.

DcimRackGroupsBulkUpdateOK dcim rack groups bulk update o k
*/
type DcimRackGroupsBulkUpdateOK struct {
	Payload *models.RackGroup
}

func (o *DcimRackGroupsBulkUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /dcim/rack-groups/][%d] dcimRackGroupsBulkUpdateOK  %+v", 200, o.Payload)
}

func (o *DcimRackGroupsBulkUpdateOK) GetPayload() *models.RackGroup {
	return o.Payload
}

func (o *DcimRackGroupsBulkUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RackGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimRackGroupsBulkUpdateDefault creates a DcimRackGroupsBulkUpdateDefault with default headers values
func NewDcimRackGroupsBulkUpdateDefault(code int) *DcimRackGroupsBulkUpdateDefault {
	return &DcimRackGroupsBulkUpdateDefault{
		_statusCode: code,
	}
}

/*DcimRackGroupsBulkUpdateDefault handles this case with default header values.

DcimRackGroupsBulkUpdateDefault dcim rack groups bulk update default
*/
type DcimRackGroupsBulkUpdateDefault struct {
	_statusCode int

	Payload interface{}
}

// Code gets the status code for the dcim rack groups bulk update default response
func (o *DcimRackGroupsBulkUpdateDefault) Code() int {
	return o._statusCode
}

func (o *DcimRackGroupsBulkUpdateDefault) Error() string {
	return fmt.Sprintf("[PUT /dcim/rack-groups/][%d] dcim_rack-groups_bulk_update default  %+v", o._statusCode, o.Payload)
}

func (o *DcimRackGroupsBulkUpdateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimRackGroupsBulkUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
